// Carboidratos aproximados por 100 g de alimento.
// Valores de referência baseados na Tabela TACO (NEPA/UNICAMP):
// https://nepa.unicamp.br/wp-content/uploads/sites/27/2023/10/taco_4_edicao_ampliada_e_revisada.pdf
const alimentos = [
  { nome: "Arroz branco cozido", carboidratosPor100g: 28.1 },
  { nome: "Arroz integral cozido", carboidratosPor100g: 25.8 },
  { nome: "Aveia em flocos crua", carboidratosPor100g: 66.6 },
  { nome: "Biscoito maisena", carboidratosPor100g: 75.2 },
  { nome: "Biscoito cream cracker", carboidratosPor100g: 68.7 },
  { nome: "Farinha de trigo", carboidratosPor100g: 75.1 },
  { nome: "Pão francês", carboidratosPor100g: 58.6 },
  { nome: "Pão integral", carboidratosPor100g: 49.9 },
  { nome: "Macarrão instantâneo", carboidratosPor100g: 62.4 },
  { nome: "Milho verde cru", carboidratosPor100g: 28.6 },
  { nome: "Milho verde enlatado", carboidratosPor100g: 17.1 },
  { nome: "Mandioca cozida", carboidratosPor100g: 30.1 },
  { nome: "Batata inglesa cozida", carboidratosPor100g: 11.9 },
  { nome: "Batata-doce cozida", carboidratosPor100g: 18.4 },
  { nome: "Manga Palmer crua", carboidratosPor100g: 19.4 },
  { nome: "Polvilho doce", carboidratosPor100g: 86.8 },
  { nome: "Cuscuz de milho cozido", carboidratosPor100g: 25.3 },
  { nome: "Feijão carioca cozido", carboidratosPor100g: 13.6 },
  { nome: "Feijão preto cozido", carboidratosPor100g: 14.0 },
  { nome: "Lentilha cozida", carboidratosPor100g: 16.3 },
  { nome: "Grão-de-bico cru", carboidratosPor100g: 57.9 },
  { nome: "Banana-prata crua", carboidratosPor100g: 26.0 },
  { nome: "Banana-nanica crua", carboidratosPor100g: 23.8 },
  { nome: "Banana-maçã crua", carboidratosPor100g: 22.3 },
  { nome: "Maçã Fuji crua", carboidratosPor100g: 15.2 },
  { nome: "Abacaxi cru", carboidratosPor100g: 12.3 },
  { nome: "Laranja-pera crua", carboidratosPor100g: 8.9 },
  { nome: "Goiaba vermelha crua", carboidratosPor100g: 13.0 },
  { nome: "Melancia crua", carboidratosPor100g: 8.1 },
  { nome: "Tomate cru", carboidratosPor100g: 3.1 },
]
